service: aws

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    DEBUG: "*"
    PAGE_LOAD_TIMEOUT: 20000
    LOGGING: true

plugins:
  - serverless-plugin-chrome
  - serverless-webpack

custom:
  chrome:
    flags:
      - --window-size=1280,1696 # Letter size
      - --hide-scrollbars

functions:
  version-info:
    description: Headless Chrome Serverless-framework version info example
    memorySize: 1024
    timeout: 30
    handler: src/handlers/version.default
    events:
      - http:
          path: version-info
          method: get

  ssr:
    description: Headless Chrome Serverless-framework SSR
    memorySize: 1536
    timeout: 15
    handler: src/handlers/ssr.default
    events:
      - http:
          path: ssr
          method: get

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"

    # Enable X-Ray tracing on Lambda functions
    # ScreenshotLambdaFunction:
    #   Properties:
    #     TracingConfig:
    #       Mode: Active
    # PdfLambdaFunction:
    #   Properties:
    #     TracingConfig:
    #       Mode: Active
